---
apiVersion: v1
kind: Template
metadata:
  name: payload-tracker-go
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: payload-tracker-go
  spec:
    envName: ${ENV_NAME}
    inMemoryDb: true
    deployments:
    - name: api
      web: true
      minReplicas: ${{API_REPLICAS}}
      podSpec:
        minReadySeconds: 15
        progressDeadlineSeconds: 600
        image: quay.io/cloudservices/payload-tracker:${IMAGE_TAG}
        command: 
          - ./pt-api
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /liveness
            port: 9000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: 9000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
        env:
          - name: LOG_LEVEL
            value: ${LOGLEVEL}

parameters:
- description: Initial amount of memory the receptor container will request.
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory the receptor.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Initial amount of cpu the receptor container will request.
  displayName: CPU Request
  name: CPU_REQUEST
  required: true
  value: 200m
- description: Maximum amount of cpu the receptor container can use.
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: 500m
- description: The log level to use for logging
  displayName: The log level to use for logging
  name: LOGLEVEL
  required: true
  value: DEBUG
- description: The number of replicas to use for the receptor gateway
  name: API_REPLICAS
  value: '1'
- description: Hostname and port of the prometheus push gateway
  name: PROMETHEUS_PUSH_GATEWAY
  value: prometheus-push.insights-push-stage.svc.cluster.local:9091
- description: Image
  name: IMAGE
  required: true
  value: quay.io/cloudservices/receptor-gateway
- description: Image tag
  name: IMAGE_TAG
  required: true
- name: ENV_NAME
  value: ${ENV_NAME}
  required: true
