version: '3.1'
services:
    payload-tracker-db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: crc
            POSTGRES_USER: crc
            POSTGRES_DB: crc
        ports:
            - "5432:5432"
